FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o dispatcher ./cmd/dispatcher

FROM public.ecr.aws/lambda/provided:al2

COPY --from=builder /app/dispatcher ./dispatcher

ENTRYPOINT [ "./dispatcher" ]
