FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker

FROM alpine:3.18

RUN apk add --no-cache ffmpeg

WORKDIR /app

COPY --from=builder /app/worker .

ENTRYPOINT ["/app/worker"]
